export const FONTSFAMILY = {
  NunitoBlack: 'Nunito-Black',
  NunitoBlackItalic: 'Nunito-BlackItalic',
  NunitoBold: 'Nunito-Bold',
  NunitoBoldItalic: 'Nunito-BoldItalic',
  NunitoExtraBold: 'Nunito-ExtraBold',
  NunitoExtraBoldItalic: 'Nunito-ExtraBoldItalic',
  NunitoExtraLight: 'Nunito-ExtraLight',
  NunitoExtraLightItalic: 'Nunito-ExtraLightItalic',
  NunitoItalic: 'Nunito-Italic',
  NunitoLight: 'Nunito-Light',
  NunitoLightItalic: 'Nunito-LightItalic',
  NunitoMedium: 'Nunito-Medium',
  NunitoMediumItalic: 'Nunito-MediumItalic',
  NunitoRegular: 'Nunito-Regular',
  NunitoSemiBold: 'Nunito-SemiBold',
  NunitoSemiBoldItalic: 'Nunito-SemiBoldItalic',

  OpenSansCondensedBold: 'OpenSans_Condensed-Bold',
  OpenSansCondensedBoldItalic: 'OpenSans_Condensed-BoldItalic',
  OpenSansCondensedExtraBold: 'OpenSans_Condensed-ExtraBold',
  OpenSansCondensedExtraBoldItalic: 'OpenSans_Condensed-ExtraBoldItalic',
  OpenSansCondensedItalic: 'OpenSans_Condensed-Italic',
  OpenSansCondensedLight: 'OpenSans_Condensed-Light',
  OpenSansCondensedLightItalic: 'OpenSans_Condensed-LightItalic',
  OpenSansCondensedMedium: 'OpenSans_Condensed-Medium',
  OpenSansCondensedMediumItalic: 'OpenSans_Condensed-MediumItalic',
  OpenSansCondensedRegular: 'OpenSans_Condensed-Regular',
  OpenSansCondensedSemiBold: 'OpenSans_Condensed-SemiBold',
  OpenSansCondensedSemiBoldItalic: 'OpenSans_Condensed-SemiBoldItalic',

  OpenSansSemiCondensedBold: 'OpenSans_SemiCondensed-Bold',
  OpenSansSemiCondensedBoldItalic: 'OpenSans_SemiCondensed-BoldItalic',
  OpenSansSemiCondensedExtraBold: 'OpenSans_SemiCondensed-ExtraBold',
  OpenSansSemiCondensedExtraBoldItalic:
    'OpenSans_SemiCondensed-ExtraBoldItalic',
  OpenSansSemiCondensedItalic: 'OpenSans_SemiCondensed-Italic',
  OpenSansSemiCondensedLight: 'OpenSans_SemiCondensed-Light',
  OpenSansSemiCondensedLightItalic: 'OpenSans_SemiCondensed-LightItalic',
  OpenSansSemiCondensedMedium: 'OpenSans_SemiCondensed-Medium',
  OpenSansSemiCondensedMediumItalic: 'OpenSans_SemiCondensed-MediumItalic',
  OpenSansSemiCondensedRegular: 'OpenSans_SemiCondensed-Regular',
  OpenSansSemiCondensedSemiBold: 'OpenSans_SemiCondensed-SemiBold',
  OpenSansSemiCondensedSemiBoldItalic: 'OpenSans_SemiCondensed-SemiBoldItalic',

  OpenSansBold: 'OpenSans-Bold',
  OpenSansBoldItalic: 'OpenSans-BoldItalic',
  OpenSansExtraBold: 'OpenSans-ExtraBold',
  OpenSansExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
  OpenSansItalic: 'OpenSans-Italic',
  OpenSansLight: 'OpenSans-Light',
  OpenSansLightItalic: 'OpenSans-LightItalic',
  OpenSansMedium: 'OpenSans-Medium',
  OpenSansMediumItalic: 'OpenSans-MediumItalic',
  OpenSansRegular: 'OpenSans-Regular',
  OpenSansSemiBold: 'OpenSans-SemiBold',
  OpenSansSemiBoldItalic: 'OpenSans-SemiBoldItalic',
}

export const Fontsfamily = {
  Nunito: {
    Black: 'Nunito-Black',
    BlackItalic: 'Nunito-BlackItalic',
    Bold: 'Nunito-Bold',
    BoldItalic: 'Nunito-BoldItalic',
    ExtraBold: 'Nunito-ExtraBold',
    ExtraBoldItalic: 'Nunito-ExtraBoldItalic',
    ExtraLight: 'Nunito-ExtraLight',
    ExtraLightItalic: 'Nunito-ExtraLightItalic',
    Italic: 'Nunito-Italic',
    Light: 'Nunito-Light',
    LightItalic: 'Nunito-LightItalic',
    Medium: 'Nunito-Medium',
    MediumItalic: 'Nunito-MediumItalic',
    Regular: 'Nunito-Regular',
    SemiBold: 'Nunito-SemiBold',
    SemiBoldItalic: 'Nunito-SemiBoldItalic',
  },

  OpenSansCondensed: {
    Bold: 'OpenSans_Condensed-Bold',
    BoldItalic: 'OpenSans_Condensed-BoldItalic',
    ExtraBold: 'OpenSans_Condensed-ExtraBold',
    ExtraBoldItalic: 'OpenSans_Condensed-ExtraBoldItalic',
    Italic: 'OpenSans_Condensed-Italic',
    Light: 'OpenSans_Condensed-Light',
    LightItalic: 'OpenSans_Condensed-LightItalic',
    Medium: 'OpenSans_Condensed-Medium',
    MediumItalic: 'OpenSans_Condensed-MediumItalic',
    Regular: 'OpenSans_Condensed-Regular',
    SemiBold: 'OpenSans_Condensed-SemiBold',
    SemiBoldItalic: 'OpenSans_Condensed-SemiBoldItalic',
  },

  OpenSansSemiCondensed: {
    Bold: 'OpenSans_SemiCondensed-Bold',
    BoldItalic: 'OpenSans_SemiCondensed-BoldItalic',
    ExtraBold: 'OpenSans_SemiCondensed-ExtraBold',
    ExtraBoldItalic: 'OpenSans_SemiCondensed-ExtraBoldItalic',
    Italic: 'OpenSans_SemiCondensed-Italic',
    Light: 'OpenSans_SemiCondensed-Light',
    LightItalic: 'OpenSans_SemiCondensed-LightItalic',
    Medium: 'OpenSans_SemiCondensed-Medium',
    MediumItalic: 'OpenSans_SemiCondensed-MediumItalic',
    Regular: 'OpenSans_SemiCondensed-Regular',
    SemiBold: 'OpenSans_SemiCondensed-SemiBold',
    SemiBoldItalic: 'OpenSans_SemiCondensed-SemiBoldItalic',
  },

  OpenSans: {
    Bold: 'OpenSans-Bold',
    BoldItalic: 'OpenSans-BoldItalic',
    ExtraBold: 'OpenSans-ExtraBold',
    ExtraBoldItalic: 'OpenSans-ExtraBoldItalic',
    Italic: 'OpenSans-Italic',
    Light: 'OpenSans-Light',
    LightItalic: 'OpenSans-LightItalic',
    Medium: 'OpenSans-Medium',
    MediumItalic: 'OpenSans-MediumItalic',
    Regular: 'OpenSans-Regular',
    SemiBold: 'OpenSans-SemiBold',
    SemiBoldItalic: 'OpenSans-SemiBoldItalic',
  },
}
