export const Icons = {
  logoApp: require('./icons/icLogo.png'),
  bkgDigital: require('./icons/bkgDigital.png'),
  icResetPass: require('./icons/icResetPass.png'),
  icAvatar: require('./icons/icAvatar.png'),
  icSettingLogin: require('./icons/icSettingLogin.png'),
  icRules: require('./icons/icRules.png'),
  icSchedule: require('./icons/icSchedule.png'),
  icFaceID: require('./icons/icFaceID.png'),
  icTouchID: require('./icons/icTouchID.png'),
  icAvatarExample: require('./icons/icAvatarExample.png'),
  icTemperature: require('./icons/icTemperature.png'),
  icHumidity: require('./icons/icHumidity.png'),
  icFan: require('./icons/icFan.png'),
  icEnergy: require('./icons/icEnergy.png'),
  icBoost: require('./icons/icBoost.png'),
  icAndroid: require('./icons/icAndroid.png'),

  drawer_menu: require('./icons/drawer_menu.png'),
  icNotification: require('./icons/icNotification.png'),

  // Example
  // ic: require(''),

  // Slider icons
  icHome: require('./icons/house-window1.png'),
  icClient: require('./icons/member-list3.png'),
  icMortgage: require('./icons/checklist-task-budget1.png'),
  icCredit: require('./icons/file-invoice-dollar.png'),
  icWork: require('./icons/dropdown-bar.png'),
  icVideo: require('./icons/icVideo.png'),
  icInteract: require('./icons/icInteract.png'),
  icExtention: require('./icons/icExtention.png'),
  icHomeSolid: require('./icons/icHomeSolid.png'),
  icClientSolid: require('./icons/icClientSolid.png'),
  icMortgageSolid: require('./icons/icMortgageSolid.png'),
  icCreditSolid: require('./icons/icCreditSolid.png'),
  icWorkSolid: require('./icons/icWorkSolid.png'),

  icTick: require('./icons/tick.png'),
  icUnTick: require('./icons/unTick.png'),
  icSearch: require('./icons/icSearch.png'),
  icFilter: require('./icons/icFilter.png'),
  icBack: require('./icons/arrow_left.png'),
  icBack_shadow: require('./icons/arrow_left_shadow.png'),

  //
  icEarth: require('./icons/earth.png'),
  icBookUser: require('./icons/book_user.png'),
  icArrowRight: require('./icons/arrow_right.png'),
  icExit: require('./icons/exit.png'),
  icUnLock: require('./icons/icUnLock.png'),
  icLock: require('./icons/icLock.png'),
  icRelative: require('./icons/icRelative.png'),
  icDropdownGroup: require('./icons/icDropdownGroup.png'),

  //
  icCheck: require('./icons/check.png'),
  icClose: require('./icons/close.png'),
  icCircleUser: require('./icons/circle-user.png'),
  icRotateReverse: require('./icons/rotate-reverse.png'),
  icPdf: require('./icons/icPdf.png'),
  icPowerPoint: require('./icons/icPP.png'),
  icWord: require('./icons/icDoc.png'),
  icExcel: require('./icons/icExcel.png'),
  icOtherFile: require('./icons/icOtherFile.png'),
  icSignFile: require('./icons/icSignFile.png'),
  icCalendar: require('./icons/calendar.png'),
  icArrowDown: require('./icons/angle-small-down.png'),
  icEmptyList: require('./icons/empty-inbox.png'),
  icNoImage: require('./icons/icNoImage.png'),
  icGalary: require('./icons/gallery.png'),
  icMortgage1: require('./icons/mortgage_1.png'),

  icVisible: require('./icons/visible_eye.png'),
  icNotVisible: require('./icons/not_visible_eye.png'),
  icReset: require('./icons/rotate.png'),
  icMoney: require('./icons/icMoney.png'),
  icTermInfo: require('./icons/icTermInfo.png'),
  icLand: require('./icons/icLand.png'),

  icUser: require('./icons/icUser.png'),
  icDropDown_2: require('./icons/icDropDown_2.png'),
  imgHaLong: require('./images/imgHaLong.jpg'),
  imgCityWater: require('./images/imgCityWater.png'),
  icChangeBackground: require('./icons/icChangeBackground.png'),
  imgDoiChe: require('./images/imgDoiChe.jpg'),
  imgDaNang: require('./images/imgDaNang.jpg'),
  icSend: require('./icons/icSend.png'),
  icSendSolid: require('./icons/icSendSolid.png'),
  icDeadline: require('./icons/icDeadline.png'),
  icGear: require('./icons/icGear.png'),
  icProcess: require('./icons/icProcess.png'),
  imgBackgroundLogin: require('./images/imgBackgroundLogin.png'),

  //Button Action WorkFlow
  icOptions: require('./icons/icOptions.png'),
  icActionEye: require('./icons/icActionEye.png'),
  icActionConfirm: require('./icons/icActionConfirm.png'),
  icActionReject: require('./icons/icActionReject.png'),
  icActionDelete: require('./icons/icActionDelete.png'),
  icActionOpinion: require('./icons/icActionOpinion.png'),
  icActionSendOpinion: require('./icons/icActionSendOpinion.png'),
  icActionUpdateProcess: require('./icons/icActionUpdateProcess.png'),
  icActionReview: require('./icons/icActionReview.png'),

  icRefund: require('./icons/icRefund.png'),
  icUndo: require('./icons/icUndo.png'),
  icCheckBadge: require('./icons/icCheckBadge.png'),
  icClosedMail: require('./icons/icClosedMail.png'),
  icOpenedMail: require('./icons/icOpenedMail.png'),

  icCheckBoxActive: require('./icons/icCheckBoxActive.png'),
  icCheckBox: require('./icons/icCheckBox.png'),
  icLoudSpeaker: require('./icons/icLoudSpeaker.png'),
  icAccessControl: require('./icons/icAccessControl.png'),
  icCashPay: require('./icons/icCashPay.png'),
  icIdea: require('./icons/icIdea.png'),
  icProjectPlan: require('./icons/icProjectPlan.png'),
};
